name: cookiecutter

on: ["push"]

jobs:
  
  cookiecutter:
    if: ${{ github.repository != 'containerly/python-http-fast' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use
    - run: pip install cookiecutter
    - run: cookiecutter https://github.com/containerly/cookiecutter-python-http-fast --no-input project_name=${GITHUB_REPOSITORY#*/} -f -o .
    - run: mv ${GITHUB_REPOSITORY#*/}/* .
    - run: rm -rf ${GITHUB_REPOSITORY#*/}
    - run: rm .github/workflows/cookiecutter.yml
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "cookiecutter"
        push_options: --force